### ISSUE TITLE
Fonctionnalités liées au panier

### ISSUE THREAD

**Issue by ThomasEscorne** [antoine-epitech/PFF_Vtest#1]
![image](https://user-images.githubusercontent.com/49443118/90517569-ddf52b00-e165-11ea-8aa9-9ee8418504d7.png)

Ajouter un bouton pour finaliser ou annuler la commande.
De plus en cas d'échec du paiement le panier n'est pas conservé, il faudrait qu'il le soit

**Comment by antoine-epitech** [comment]
Le panier est maintenant conservé, et les commandes sont annulables.

**Comment by ThomasEscorne** [comment]
Je viens de tester, mettre des items dans le panier puis clicker sur payer ne redirige plus vers le tunnel de paiement mais vers la page "Mes commandes", où il n'est toujours pas possible de payer ni annuler une commande.
